-- V20251126__create_payout_email.sql
-- Tabela para logar envios de e-mail de repasse (PIX e Cartão)

CREATE TABLE IF NOT EXISTS payout_email (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payout_id     BIGINT        NOT NULL,
  to_email      VARCHAR(255)  NOT NULL,
  email_type    VARCHAR(40)   NOT NULL,              -- 'REPASSE_PIX', 'REPASSE_CARD', etc.
  sent_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  status        VARCHAR(20)   NOT NULL,              -- 'SENT', 'FAILED'
  error_message TEXT
);

-- FK para payment_payouts (on delete cascade para manter consistência)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname='fk_payout_email_payout_id'
  ) THEN
    ALTER TABLE payout_email
      ADD CONSTRAINT fk_payout_email_payout_id
      FOREIGN KEY (payout_id)
      REFERENCES payment_payouts(id)
      ON DELETE CASCADE;
  END IF;
END$$;

-- Status válidos
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname='chk_payout_email_status'
  ) THEN
    ALTER TABLE payout_email
      ADD CONSTRAINT chk_payout_email_status
      CHECK (status IN ('SENT', 'FAILED'));
  END IF;
END$$;

-- Índices para consultas comuns
CREATE INDEX IF NOT EXISTS idx_payout_email_payout_id ON payout_email(payout_id);
CREATE INDEX IF NOT EXISTS idx_payout_email_status ON payout_email(status);
CREATE INDEX IF NOT EXISTS idx_payout_email_sent_at ON payout_email(sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_payout_email_type ON payout_email(email_type);

